backend/src/buildRequest.ts, backend/src/controllers/index.controller.ts, backend/src/runRequest.ts, backend/src/types/body.ts, backend/src/types/requestBodyInterface.ts, backend/src/types/requestInput.ts, backend/src/types/requestInputPost.ts, backend/src/types/result.ts, backend/tests/test_query_params.sh
A first request with a parameter *scrol* is needed, for example: 
```bash
curl -s -X POST -H "Content-Type: application/json" -d '{"firstName": "Jean", "scroll": "1m"}' http://localhost:9200/deces/api/v1/search
```
This returns a field scrollId, which need to be included in the next request in order to get the next batch of results. Like the following:
```bash
curl -s -X POST -H "Content-Type: application/json" -d '{"scroll": "1m", "scrollId": "thisIsMyScrollId"}' http://localhost:9200/deces/api/v1/search 
```
=> ES scroll parameter support

backend/src/controllers/index.controller.ts, backend/src/types/requestInputPost.ts, backend/src/types/result.ts
Add more information to tsc interfaces to improve the swagger.yml file and interface
Remove duplicated example for get and post request
=> ♻ Move examples to tsc interfaces

.github/workflows/dockerimage.yml, .gitignore, Makefile, backend/package-lock.json, backend/package.json, backend/src/controllers/bulk.ts, backend/src/controllers/index.controller.ts, backend/src/index.ts, backend/src/runRequest.ts, docker-compose-dev-backend.yml, docker-compose.yml
* `/search/csv` and `/search/json` launch a job with the csv passed as a parameter and returns a job id.
* `/search/:format/:jobId` returns the status of the job, if running it will tell the progress. If the job has finished, then it will return the result in the requested format (available csv and json)
The requests are done sequentially by chunks using msearch elasticsearch API.
Optimizations:
=> Use redis as a ticketing system for bulk request

backend/package-lock.json, backend/package.json, backend/src/controllers/bulk.ts, backend/src/controllers/documentation.ts, backend/src/controllers/index.controller.ts, backend/src/index.ts, docker-compose-dev-backend.yml
The swagger documentation is the combination of two swagger files:
* A swagger.json file is generated automatically by `tsoa` using typescript static typings
* A swagger.json file is generated with jsdocs using `swagger-jsdoc`
The swagger documentation is available at `/deces/api/v1/docs`
=> Add swagger documentation for bulk search routes

backend/src/controllers/bulk.ts
All query fields (birthCity, etc.), can now be set in a column so that a user can use complex queries row by row
=> extend csv columns to all possible search query params

.github/workflows/dockerimage.yml, backend/src/controllers/bulk.ts
1. An encryption key is created using a the [fortuna](https://github.com/digitalbazaar/forge#prng) pseudo random generator from forge-node. 
2. Bulk matching results are encrypted using block cipher CBC mode AES
3. The encrypted job results are identified using the hash (sha256) of the encryption key. 
4. The encryption key is given to the user when the job is submitted and destroyed after that.
1. The user submits the encryption key to get the results
2. The results are found using the hash of the decryption key 
3. The results are decrypted using the encryption key and send to the user.
Results are deleted 1 hour after the job finishes.
=> 🔒 Crypt bulk data

backend/package-lock.json, backend/package.json, backend/src/controllers/index.controller.ts, backend/src/controllers/index.spec.ts, backend/src/score.spec.ts, backend/src/score.ts
Mocha allows to establish test functions and components
For the moment this is only for dev environment,  it's not included in CI tests
=> Add mocha test

backend/package-lock.json, backend/package.json, backend/src/controllers/bulk.spec.ts, backend/src/controllers/bulk.ts
Fast-csv simplifies csv parsing and adds more options like escaping, quotes, trims and ignore empty rows.
In addition it uses a nodejs stream, it's better for reading large csv.
=> Use fast csv to parse csv file

backend/src/controllers/bulk.ts
Fast csv format alows simple quoting and escape of csv output.
For example: 
```
[
'PhD, PP',
'',
'FRANCE',
'LE HAVRE',
'16/05/1999',
'MATTHIAS',
undefined
] 
```
results in:
```
"PhD, PP",,FRANCE,LE HAVRE,16/05/1999,MATTHIAS,
```
=> ✨ use fast csv to format output csv

backend/src/buildRequest.ts, backend/src/controllers/bulk.ts, backend/src/controllers/index.controller.ts, backend/src/fieldsWithQueries.ts, backend/src/masks.ts, backend/src/models/entities.ts, backend/src/models/requestInput.ts, backend/src/models/result.ts, backend/tests/test_query_params.sh
=> 👌Implementing swagger description from @mogador26

backend/package.json, backend/src/controllers/bulk.ts, backend/src/controllers/index.controller.ts, backend/src/masks.ts, backend/src/models/requestInput.ts, backend/src/queries.ts
=> 🗃 File system save and before/after queries

Makefile
at curl test procedure to wait for express service being up.
=> wait for backend service being up

Makefile, backend/package-lock.json
consider backend started after api being reachable
=> fix start with test

backend/src/controllers/bulk.ts
=> fix bulk progress report with multiple candidates

.github/workflows/dockerimage.yml, Makefile, backend/src/controllers/bulk.ts, backend/src/controllers/index.controller.ts, backend/src/index.spec.ts, docker-compose-dev-backend.yml
Order results depending on the column used to match.
Update tests:
Fixes #98
=> 🔀 Order results in bulk mode

.github/workflows/dockerimage.yml, Makefile, backend/src/controllers/bulk.ts, backend/src/index.spec.ts, backend/src/index.ts, backend/src/logger.ts, backend/src/server.spec.ts, backend/src/server.ts
Csv can have unmatched columns numbers like:
```
Prenom,Nom,Date,Sex
jean,pierre,dupont,04/08/1933,Marseille,M
georges,michel,john,steven,12/03/1939,M
```
This PR catches this error in the backend and gives the user an error message to solve the problem.
=> 🥅 Catch error for bad csv format

backend/src/controllers/index.controller.ts, backend/src/server.spec.ts
=> 💄 Remove scores and id for export csv function

backend/package-lock.json, backend/package.json, backend/src/controllers/bulk.ts, backend/src/server.spec.ts
Bump bee queue version, fix some new typings definitions
Fix swagger format parsing bug for swagger-ui-svelte
=> ⬆️ Upgrade bee queue

backend/src/score.ts
Accept Hollande as a country.
Accept "H" as male value for sex score calculation
=> ⚗ Small hacks score

backend/src/models/result.ts, backend/src/score.ts
* Use INSEE UID as ID
* Small hacks for sex and country score calculation
=> Add INSEE ID and some small hacks for score calculation

backend/src/buildRequest.ts, backend/src/controllers/bulk.spec.ts, backend/src/controllers/bulk.ts, backend/src/controllers/index.controller.ts, backend/src/controllers/index.spec.ts, backend/src/fieldsWithQueries.ts, backend/src/models/entities.ts, backend/src/models/requestInput.ts, backend/src/models/result.ts, backend/src/queries.ts, backend/src/score.ts
=> ✨ Add legalName field

backend/src/buildRequest.ts, backend/src/controllers/aggregation.controller.ts, backend/src/controllers/bulk.controller.ts, backend/src/controllers/documentation.ts, backend/src/controllers/search.controller.ts, backend/src/controllers/search.spec.ts, backend/src/controllers/status.controller.ts, backend/src/models/entities.ts, backend/src/server.spec.ts, backend/src/server.ts
* Add documentation for aggregations endpoint
* Separate route controller depending on groups of functions.
* Add swagger description for groups
=> 🚚 Rename & separate controllers, add documentation for aggregations

backend/src/buildRequest.ts, backend/src/controllers/aggregation.controller.ts, backend/src/models/requestInput.ts, backend/src/server.spec.ts
=> ✨ add aggregation bucket size (default 15) for large vocabulary fields

backend/src/controllers/aggregation.controller.ts
=> ✨ Accept aggregation without search parameters

backend/src/controllers/search.controller.ts, backend/src/controllers/search.spec.ts, backend/src/fieldsWithQueries.ts, backend/src/masks.ts, backend/src/models/requestInput.ts, backend/src/processStream.ts
=> ✨ Use INSEE file as a query parameter for search

backend/package-lock.json, backend/package.json, backend/src/score.ts, backend/src/types/@jollie/index.d.ts
=> ⬆️  move @thejellyfish to @jollie and upgrade

backend/src/controllers/aggregation.controller.ts, backend/src/controllers/search.controller.ts
Résolu un bug au moment de faire un stream des réponses avec express. Notamment pour les routes `/agg` et `/search`
=> 🐛 Explicitly close request for stream request

docker-compose.yml
=> 🔧 restrict data volume to proofs

backend/src/controllers/search.controller.ts
=> 🐛 fix API proof file when contains a "-"

backend/src/controllers/job.controller.ts, backend/src/server.spec.ts
Pour lister le nombre de jobs par type de file on peut utiliser la route publique:
```
/deces/api/v1/queue?name=jobs
```
Pour recuperer la liste de jobs avec plus d'information on peut utiliser:
```
/deces/api/v1/queue/jobs
```
On peut filtrer par type ou par id avec les query parameters jobsType et jobId. On peut utiliser la pagination avec les query parameters start, end et size.
=> Filtrer les jobs avec un query parameter

backend/src/controllers/job.controller.ts
=> 💥 Remove random key from job list

Makefile
Séparer la récupération des données de l'analyse des données et génération du dashboard de viz avec clininc.js
ça permet de diminuer la mémoire vive utilisé qui peut faire planter clinic.js
Fixes #244
=> 🎨 Fix clinic.js random crash

backend/src/controllers/search.controller.ts, backend/src/models/entities.ts, backend/src/score.spec.ts, backend/src/score.ts, backend/src/server.spec.ts
+ suppression de quelques warnings du linter
=> 📮 Utiliser le code postal dans le calcul du score

backend/tests/test_query_params.sh
grep versions in BusyBox don't support "grep -oP"
=> 🔧 Grep on alpine  doesn't support -P or --invert-match

Makefile, backend/src/communes.ts, backend/src/logger.ts
Le [lien vers le fichiers de communes](https://etalab-datasets.geo.data.gouv.fr/contours-administratifs/2019/geojson/) est down.
On peut utiliser ce fichier du portail data.gouv.fr
=> 🗺 Download communes file from data.gouv.fr

backend/src/score.ts
=> 🐛 Error raised in ScoreName when undefined

backend/src/controllers/auth.controller.ts, backend/src/server.spec.ts
* When verifying token validity, we can obtain token creation and expiration dates.
* Authentication can be made with an already valid token, this will create a new token with 30 days more of validity. A token can be refreshed with a limit of 11 months.
=> ✨  Add token details and refresh

backend/src/controllers/auth.controller.ts, backend/src/controllers/documentation.ts, backend/src/mail.spec.ts, backend/src/mail.ts, backend/src/models/entities.ts, backend/src/server.spec.ts, backend/src/server.ts
* Block disposable providers using the list from [adamloving/4401361](https://gist.github.com/adamloving/4401361). 
* Add documentation for auth recent modifications
=> 💂 Block disposable mails providers

Makefile, README.md
* Github badge has been updated
* Clinicjs report fixed
=> 🏥  Fix clinicjs report creation

backend/src/controllers/auth.controller.ts
Adds info on access token like expiration date and renewal limit date to enable easied display of information about API Key in deces-ui
=> adds info of expiration & renewal limit on all auth responses
